[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
wal = { path = "../wal" }
schemas = { path = "../schemas" }
tracing.workspace=true
tracing-subscriber.workspace=true
tonic.workspace=true
tonic-health.workspace=true
tokio.workspace=true
anyhow.workspace=true