[package]
name = "wal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
mlg.workspace = true
tokio.workspace = true
serde = { version = "1.0.192", features = ["derive"] }